@startuml


	skinparam {
		Style strictuml
		
	 
		
	 
	}
	 
	title Add New Product
	 
	actor User as user
	participant "Administration" as main <<main>>
	main++
	
    create "ProductAdministration" as menu <<frame>>
    main -> menu : construct
    
    main -> menu: setVisible(true)
    menu++
    
    user -> menu: clicks Add New Product
    
    create "ProductEditor" as editor <<dialog>>
  
    
    menu -> editor : construct
    editor++

   'creates a Data Access Object
   create "DAO" as dao <<DAO>>
   editor -> dao : construct
   
   editor -> dao: getCategories()
   dao++
   return categories
   
   'creates a SimpleListModel to help 
   create "SimpleListModel" as helper <<model>>
   editor -> helper : construct
   
   editor-> helper : updateItems(categories)
   editor -> editor : categoryBox.setModel(model)
   editor--

    user -> editor++ : Enters product details
    editor--
    
    user -> editor++ : Clicks Save Button
    editor++
    
    create "Product" as product <<domain>>
    editor -> product : construct
    
    editor -> editor: get product details entered in GUI components
    
    editor -> product++: set product details
    product--
    
    editor -> dao++ : save(product)
    editor->editor: dispose()
    destroy editor
    
    



@enduml
