@startuml
skinparam {
		Style strictuml
	}

/'
Sequence Diagram adapted from Sequence Diagram snippet shown in lecture 16
'/
	 

actor "User" as user

participant "Products Page" as browser <<Web Browser>>

user->browser++: clicks Browse Products

participant "Product Controller" as prodCtrl <<JS>>

browser->prodCtrl++:  productDAO.query()

participant "Product Module" as productModule <<Jooby>>


prodCtrl->productModule++: GET/api/products

participant "ProductDBManager" as dao 

productModule->dao++: getProducts()

participant "Database" as db

dao->db++: select * from Product

return ResultSet

return products
return json products
loop ng-repeat prodCtrl

return products are displayed by ng-repeat
end
return user sees products

@enduml
